package docker

import "fmt"

// PostgreSQLDefaultTag Default tag for PostgreSQL
const PostgreSQLDefaultTag = "9.6-alpine"

// PostgreSQLRepository Namespace for the official Docker releases for PostgreSQL
const PostgreSQLRepository = "postgres"

// PostgreSQL represents a PostgreSQL image
type PostgreSQL struct {
	LpnType string
	Tag     string
}

// GetContainerName returns the name of the container generated by this type of image
func (p PostgreSQL) GetContainerName() string {
	return "db-" + p.GetLpnType()
}

// GetDataFolder returns the data folder for the database
func (p PostgreSQL) GetDataFolder() string {
	return "/var/lib/postgresql/data"
}

// GetDockerHubTagsURL returns the URL of the available tags on Docker Hub
func (p PostgreSQL) GetDockerHubTagsURL() string {
	return "postgresql"
}

// GetEnvVariables returns the specific environment variables to configure the docker image
func (p PostgreSQL) GetEnvVariables() EnvVariables {
	return EnvVariables{
		Database: "POSTGRES_DB=" + DBName,
		Password: "POSTGRES_PASSWORD=" + DBPassword,
		User:     "POSTGRES_USER=" + DBUser,
	}
}

// GetJDBCConnection returns the JDBC connection
func (p PostgreSQL) GetJDBCConnection() JDBCConnection {
	return JDBCConnection{
		DriverClassName: "org.postgresql.Driver",
		Password:        DBPassword,
		URL:             fmt.Sprintf("jdbc:postgresql://%s:%d/%s", GetAlias(), p.GetPort(), DBName),
		User:            DBUser,
	}
}

// GetFullyQualifiedName returns the fully qualified name of the image
func (p PostgreSQL) GetFullyQualifiedName() string {
	return p.GetRepository() + ":" + p.GetTag()
}

// GetLpnType returns the type of the lpn image
func (p PostgreSQL) GetLpnType() string {
	return p.LpnType
}

// GetPort returns the bind port of the service
func (p PostgreSQL) GetPort() int {
	return 5432
}

// GetRepository returns the repository for PostgreSQL
func (p PostgreSQL) GetRepository() string {
	return PostgreSQLRepository
}

// GetTag returns the tag of the image
func (p PostgreSQL) GetTag() string {
	if p.Tag == "" {
		return PostgreSQLDefaultTag
	}

	return p.Tag
}

// GetType returns the type of the image
func (p PostgreSQL) GetType() string {
	return "postgresql"
}
