// Copyright (c) 2000-present Liferay, Inc. All rights reserved.
//
// This library is free software; you can redistribute it and/or modify it under
// the terms of the GNU Lesser General Public License as published by the Free
// Software Foundation; either version 2.1 of the License, or (at your option)
// any later version.
//
// This library is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
// details.

package liferay

import internal "github.com/mdelapenya/lpn/internal"

// Commerce implementation for Liferay nightly images with Commerce
type Commerce struct {
	Tag string
}

// GetContainerName returns the name of the container generated by this type of image
func (c Commerce) GetContainerName() string {
	return internal.LpnConfig.GetPortalContainerName("commerce")
}

// GetDeployFolder returns the deploy folder under Liferay Home
func (c Commerce) GetDeployFolder() string {
	return c.GetLiferayHome() + "/deploy"
}

// GetDockerHubTagsURL returns the URL of the available tags on Docker Hub
func (c Commerce) GetDockerHubTagsURL() string {
	return "liferay/commerce"
}

// GetFullyQualifiedName returns the fully qualified name of the image
func (c Commerce) GetFullyQualifiedName() string {
	return c.GetRepository() + ":" + c.GetTag()
}

// GetLiferayHome returns the Liferay home for nightly builds with Commerce
func (c Commerce) GetLiferayHome() string {
	return "/opt/liferay"
}

// GetRepository returns the repository for nightly builds with Commerce
func (c Commerce) GetRepository() string {
	return internal.LpnConfig.GetPortalImageName("commerce")
}

// GetTag returns the tag of the image
func (c Commerce) GetTag() string {
	return c.Tag
}

// GetType returns the type of the image
func (c Commerce) GetType() string {
	return "commerce"
}

// GetUser returns the user running the main application
func (c Commerce) GetUser() string {
	return "liferay"
}
