package liferay

// Nightly implementation for Liferay nightly images
type Nightly struct {
	Tag string
}

// GetContainerName returns the name of the container generated by this type of image
func (n Nightly) GetContainerName() string {
	return "lpn-" + n.GetType()
}

// GetDeployFolder returns the deploy folder under Liferay Home
func (n Nightly) GetDeployFolder() string {
	return n.GetLiferayHome() + "/deploy"
}

// GetDockerHubTagsURL returns the URL of the available tags on Docker Hub
func (n Nightly) GetDockerHubTagsURL() string {
	return "mdelapenya/liferay-portal-nightlies"
}

// GetFullyQualifiedName returns the fully qualified name of the image
func (n Nightly) GetFullyQualifiedName() string {
	return n.GetRepository() + ":" + n.GetTag()
}

// GetLiferayHome returns the Liferay home for nightly builds
func (n Nightly) GetLiferayHome() string {
	return "/liferay"
}

// GetRepository returns the repository for nightly builds
func (n Nightly) GetRepository() string {
	return NightliesRepository
}

// GetTag returns the tag of the image
func (n Nightly) GetTag() string {
	return n.Tag
}

// GetType returns the type of the image
func (n Nightly) GetType() string {
	return "nightly"
}
