name: Unit Tests

on:
  push:
    branches:    
      - develop
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Run Unit tests
        run: |
          go get -u gotest.tools/gotestsum
          gotestsum --format short-verbose ./...
