name: Tests

on:
  push:
    branches:    
      - develop
      - master
  pull_request:
    branches:
      - master
      - develop

env:
  GO111MODULE: on

jobs:
  tests:
    name: Unit and E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.25
        uses: actions/setup-go@v3
        with:
          go-version: '1.25'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v -o ./bin/lpn .

      - name: Run Unit tests
        run: |
          go install gotest.tools/gotestsum@latest
          gotestsum --format short-verbose $(go list ./... | grep -v /e2e)

      - name: Run E2E tests
        run: go test -v ./e2e/... -timeout 30m
