name: End-To-End tests

on:
  push:
    branches:    
      - develop
      - master
  pull_request:
    branches:
      - master
      - develop

env:
  GO111MODULE: on

jobs:
  build:
    name: End-2-End Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: [checkc, checki, deploy, license, pull, rm, rmi, run, start, stop, tags, version]
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          sudo gem update --system 3.3.18
          sudo gem install bundler
          sudo bundle install
          go get -v -t -d ./...

      - name: Build
        run: go build -o ./bin/lpn

      - name: Run E2E tests
        run: cucumber features/${{ matrix.command }}.feature
